# Site settings
title: Nii Martey
header-img: img/home-bg.jpg
email: niimartey@niimartey.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/Blog"
url: "http://niiimartey.com"
twitter_username: niimartey
github_username:  NiiMartey
facebook_username:  niimartey

# Build settings
#markdown: kramdown
markdown: redcarpet
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
